spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          connection:
            provider_disables_autocommit: false
          show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/mydata
    username: root
    password: 870925
    driver-class-name: com.mysql.cj.jdbc.Driver
