spring:
  application:
    name: library-demo
  profiles:
    active: local
    include:
      - user
      - book
      - infra
  mvc:
    path-match:
      matching-strategy: ant_path_matcher

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
